name: Auto Deploy Selected API Files to aaPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: ${{ github.actor == 'SyedJasmine1991' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Prepare Deploy Package (Only routes + App.js)
        run: |
          mkdir deploy
          cp App.js deploy/
          cp -r routes deploy/

          # Create archive
          cd deploy
          zip -r api-update.zip . 
          cd ..

      - name: Upload to aaPanel
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          source: "deploy/api-update.zip"
          target: "/www/wwwroot/66.29.149.122/amproAdminapi/"

      - name: SSH â†’ Deploy on Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /www/wwwroot/66.29.149.122/amproAdminapi/
            
            unzip -o api-update.zip
            rm api-update.zip

            pm2 restart amproAdminapi
